spring:
  application:
    name: kono
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.MySQLDialect

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            redirect-uri: ${KAKAO_REDIRECT_URI}
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            scope:
              - profile_nickname
              - profile_image
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize?prompt=login
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

  web:
    cors:
      allowed-origins:
        - ${FRONTEND_REDIRECT_URI}
        - http://localhost:5173  # 개발 환경용
      allowed-methods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
      allowed-headers:
        - "*"
      allow-credentials: true
      max-age: 3600

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_ACCESS_KEY}
    region:
      static: ${AWS_REGION}
    s3:
      bucket: ${AWS_BUCKET_NAME}
      base-url: ${CLOUDFRONT_URL}
      allowed-origins:
        - ${FRONTEND_REDIRECT_URI}
        - http://localhost:5173

thymeleaf:
  enabled: true
  prefix: classpath:/templates/
  suffix: .html
  cache: false
  check-template-location: true

mvc:
  view:
    prefix: /templates/
    suffix: .html

logging:
  level:
    org.springframework.security: INFO
    org.springframework.web.client.RestTemplate: INFO
    org.hibernate: ERROR
    org.hibernate.SQL: ERROR
    org.hibernate.type.descriptor.sql: ERROR

server:
  port: 8080  # Nginx에서 리버스 프록시로 사용할 포트
  forward-headers-strategy: FRAMEWORK  # Nginx 프록시 헤더 처리
  servlet:
    session:
      timeout: 30m  # 세션 만료 시간
      cookie:
        name: SESSIONID
        http-only: true
        secure: true  # HTTPS 사용시 true로 변경
      tracking-modes: cookie  # URL 재작성 비활성화
    encoding:
      charset: UTF-8
      force: true

# 업비트 API 설정
upbit:
  api:
    url: https://api.upbit.com/v1

# 프로덕션 환경 설정 추가
custom:
  domain: ${FRONTEND_REDIRECT_URI}
  production: true

# 여기서부터 project
project:
  success-url:
    main: ${SUCCESS_URL_MAIN:https://www.playkono.com}
    dev:  ${SUCCESS_URL_DEV:https://dev.playkono.com}
    local: ${SUCCESS_URL_LOCAL:http://localhost:5173}

  allow-origin:
    main: ${ALLOW_ORIGIN_MAIN:https://www.playkono.com}
    dev:  ${ALLOW_ORIGIN_DEV:https://dev.playkono.com}
    local: ${ALLOW_ORIGIN_LOCAL:http://localhost:5173}

frontend:
  redirect-uri: ${FRONTEND_REDIRECT_URI}
  cloud-front: ${CLOUD_FRONT_URL}

