name: Backend CI/CD

on:
  push:
    branches: [ "main" ]
 
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Build Spring Boot App
      run: ./gradlew build -x test

    - name: Setup SSH Key (base64 decode)
      run: |
        
        echo "${{ secrets.EC2_PRIVATE_KEY_B64 }}" | base64 -d > key.pem
        chmod 400 key.pem
        
    - name: Register Public Key on EC2
      run: |
        ssh -i key.pem -o StrictHostKeyChecking=no ubuntu@3.36.226.164 "
          mkdir -p ~/.ssh && chmod 700 ~/.ssh
          touch ~/.ssh/authorized_keys
          grep -qxF \"$(cat id_rsa.pub)\" ~/.ssh/authorized_keys || echo \"$(cat id_rsa.pub)\" >> ~/.ssh/authorized_keys
          chmod 600 ~/.ssh/authorized_keys
        "
      
    - name: SCP JAR to EC2
      run: scp -i key.pem -o StrictHostKeyChecking=no build/libs/*.jar ubuntu@3.36.226.164:/home/ubuntu/backend/

    - name: SSH & Restart Service
      run: |
        ssh -v -i key.pem -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ubuntu@3.36.226.164 "
          sh -c '
            set +e
            pkill -f "java -jar" || true
            nohup java -jar /home/ubuntu/backend/*.jar --server.port=8080 > /home/ubuntu/backend/app.log 2>&1 &
          '
        "
